// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using training_backend.Data;

#nullable disable

namespace training_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260603081520_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("training_backend.Models.Entities.Department", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("training_backend.Models.Entities.FeedbackAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FeedbackSubmissionId")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FeedbackSubmissionId");

                    b.ToTable("FeedbackAnswers");
                });

            modelBuilder.Entity("training_backend.Models.Entities.FeedbackSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TraineeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrainingSessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainingSessionId");

                    b.ToTable("FeedbackSubmissions");
                });

            modelBuilder.Entity("training_backend.Models.Entities.FollowUp", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationExtent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssessmentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Barriers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ImprovementObserved")
                        .HasColumnType("bit");

                    b.Property<string>("SupervisorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SupportNeeded")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("SupervisorId");

                    b.ToTable("FollowUp");
                });

            modelBuilder.Entity("training_backend.Models.Entities.KnowledgeAssessment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AssessedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssessmentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("DemonstratedUnderstanding")
                        .HasColumnType("bit");

                    b.Property<bool>("IndependentPerformance")
                        .HasColumnType("bit");

                    b.Property<string>("TraineeFeedbackId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("TraineeFeedbackId");

                    b.ToTable("KnowledgeAssessment");
                });

            modelBuilder.Entity("training_backend.Models.Entities.Report", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AssessmentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PdfUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentId");

                    b.ToTable("Report");
                });

            modelBuilder.Entity("training_backend.Models.Entities.TraineeAssessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanPerformIndependently")
                        .HasColumnType("bit");

                    b.Property<bool>("DemonstratedUnderstanding")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TraineeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrainerReportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainerReportId");

                    b.ToTable("TraineeAssessments");
                });

            modelBuilder.Entity("training_backend.Models.Entities.TraineeFeedback", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AssessmentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContentRelevant")
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Effectiveness")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ObjectivesClear")
                        .HasColumnType("int");

                    b.Property<int>("PaceAppropriate")
                        .HasColumnType("int");

                    b.Property<int>("PracticalUseful")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrainerKnowledge")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentId");

                    b.ToTable("TraineeFeedback");
                });

            modelBuilder.Entity("training_backend.Models.Entities.TrainerReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EffectivenessRating")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Improvements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("OverallPassRate")
                        .HasColumnType("float");

                    b.Property<bool>("PerformanceImproved")
                        .HasColumnType("bit");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkillApplicationLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SubmittedToSupervisor")
                        .HasColumnType("bit");

                    b.Property<string>("SupervisorComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SupervisorDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SupervisorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupervisorSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupervisorSignatureStatus")
                        .HasColumnType("int");

                    b.Property<string>("SupportNeeded")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrainerComment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TrainerDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrainerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrainerSignature")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrainerSignatureStatus")
                        .HasColumnType("int");

                    b.Property<int>("TrainingSessionId")
                        .HasColumnType("int");

                    b.Property<string>("WhatWorkedWell")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TrainingSessionId")
                        .IsUnique();

                    b.ToTable("TrainerReports");
                });

            modelBuilder.Entity("training_backend.Models.Entities.TrainingAssessment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AssessmentCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChangeFuture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EffectivenessRating")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeedbackLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberOfTrainees")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QrCodeUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recommendation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SupervisorSignoffDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SupervisorSignoffName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupervisorSignoffSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupervisorSignoffSignatureData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupervisorSignoffSignatureType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrainerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TrainerRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TrainerSignoffDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrainerSignoffName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrainerSignoffSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrainerSignoffSignatureData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrainerSignoffSignatureType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TrainingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("WorkedWell")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TrainerId");

                    b.ToTable("TrainingAssessment");
                });

            modelBuilder.Entity("training_backend.Models.Entities.TrainingObjective", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AssessmentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrainingSessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("TrainingSessionId");

                    b.ToTable("TrainingObjectives");
                });

            modelBuilder.Entity("training_backend.Models.Entities.TrainingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedSupervisorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DraftPayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DurationDays")
                        .HasColumnType("int");

                    b.Property<int?>("DurationHours")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FeedbackClosesAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NumberOfTrainees")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SubmittedPayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetAudience")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrainerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TrainingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrainingFormat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedSupervisorId");

                    b.ToTable("TrainingSessions");
                });

            modelBuilder.Entity("training_backend.Models.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SupervisorId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("SupervisorId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("training_backend.Models.Entities.FeedbackAnswer", b =>
                {
                    b.HasOne("training_backend.Models.Entities.FeedbackSubmission", "FeedbackSubmission")
                        .WithMany("Answers")
                        .HasForeignKey("FeedbackSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeedbackSubmission");
                });

            modelBuilder.Entity("training_backend.Models.Entities.FeedbackSubmission", b =>
                {
                    b.HasOne("training_backend.Models.Entities.TrainingSession", "TrainingSession")
                        .WithMany("FeedbackSubmissions")
                        .HasForeignKey("TrainingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingSession");
                });

            modelBuilder.Entity("training_backend.Models.Entities.FollowUp", b =>
                {
                    b.HasOne("training_backend.Models.Entities.TrainingAssessment", "Assessment")
                        .WithMany("FollowUps")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("training_backend.Models.Entities.User", "Supervisor")
                        .WithMany("FollowUps")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Assessment");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("training_backend.Models.Entities.KnowledgeAssessment", b =>
                {
                    b.HasOne("training_backend.Models.Entities.TrainingAssessment", "Assessment")
                        .WithMany("Evaluations")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("training_backend.Models.Entities.TraineeFeedback", "TraineeFeedback")
                        .WithMany("Evaluations")
                        .HasForeignKey("TraineeFeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");

                    b.Navigation("TraineeFeedback");
                });

            modelBuilder.Entity("training_backend.Models.Entities.Report", b =>
                {
                    b.HasOne("training_backend.Models.Entities.TrainingAssessment", "Assessment")
                        .WithMany("Reports")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");
                });

            modelBuilder.Entity("training_backend.Models.Entities.TraineeAssessment", b =>
                {
                    b.HasOne("training_backend.Models.Entities.TrainerReport", "TrainerReport")
                        .WithMany("TraineeAssessments")
                        .HasForeignKey("TrainerReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainerReport");
                });

            modelBuilder.Entity("training_backend.Models.Entities.TraineeFeedback", b =>
                {
                    b.HasOne("training_backend.Models.Entities.TrainingAssessment", "Assessment")
                        .WithMany("Feedbacks")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");
                });

            modelBuilder.Entity("training_backend.Models.Entities.TrainerReport", b =>
                {
                    b.HasOne("training_backend.Models.Entities.TrainingSession", "TrainingSession")
                        .WithOne("TrainerReport")
                        .HasForeignKey("training_backend.Models.Entities.TrainerReport", "TrainingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingSession");
                });

            modelBuilder.Entity("training_backend.Models.Entities.TrainingAssessment", b =>
                {
                    b.HasOne("training_backend.Models.Entities.User", "Trainer")
                        .WithMany("Assessments")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("training_backend.Models.Entities.TrainingObjective", b =>
                {
                    b.HasOne("training_backend.Models.Entities.TrainingAssessment", "Assessment")
                        .WithMany("Objectives")
                        .HasForeignKey("AssessmentId");

                    b.HasOne("training_backend.Models.Entities.TrainingSession", "TrainingSession")
                        .WithMany("Objectives")
                        .HasForeignKey("TrainingSessionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Assessment");

                    b.Navigation("TrainingSession");
                });

            modelBuilder.Entity("training_backend.Models.Entities.TrainingSession", b =>
                {
                    b.HasOne("training_backend.Models.Entities.User", "AssignedSupervisor")
                        .WithMany()
                        .HasForeignKey("AssignedSupervisorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AssignedSupervisor");
                });

            modelBuilder.Entity("training_backend.Models.Entities.User", b =>
                {
                    b.HasOne("training_backend.Models.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("training_backend.Models.Entities.User", "Supervisor")
                        .WithMany("SupervisedTrainers")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Department");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("training_backend.Models.Entities.Department", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("training_backend.Models.Entities.FeedbackSubmission", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("training_backend.Models.Entities.TraineeFeedback", b =>
                {
                    b.Navigation("Evaluations");
                });

            modelBuilder.Entity("training_backend.Models.Entities.TrainerReport", b =>
                {
                    b.Navigation("TraineeAssessments");
                });

            modelBuilder.Entity("training_backend.Models.Entities.TrainingAssessment", b =>
                {
                    b.Navigation("Evaluations");

                    b.Navigation("Feedbacks");

                    b.Navigation("FollowUps");

                    b.Navigation("Objectives");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("training_backend.Models.Entities.TrainingSession", b =>
                {
                    b.Navigation("FeedbackSubmissions");

                    b.Navigation("Objectives");

                    b.Navigation("TrainerReport");
                });

            modelBuilder.Entity("training_backend.Models.Entities.User", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("FollowUps");

                    b.Navigation("SupervisedTrainers");
                });
#pragma warning restore 612, 618
        }
    }
}
